infrastructure = [
    "Broadband infrastructure",
    "Internet infrastructure",
    "Network infrastructure",
    "Connectivity infrastructure",
    "Fiber infrastructure",
    "Broadband connectivity",
    "Broadband",
    "digital inclusion",
    "network connectivity",
    "Telecommunications",
    "Mobile operator",
    "Telecom operator",
    "Network operator",
    "Submarine network",
    "Submarine cable",
    "Satellite",
    "Cable landing",
    "Internet cable",
    "Submarine fiber",
    "Submarine connectivity",
    "virtual landing station",
    "cross-border connectivity",
    "international gateway",
    "Backbone network",
    "national backbone",
    "fiber backbone",
    "microwave backbone",
    "backhaul network",
    "Local access network",
    "Fiber-to-the-home",
    "FTTH",
    "WIFI",
    "public access point",
    "community center",
    "local loop network",
    "universal service fund (USF)",
    "universal access fund (UAF)",
    "USAF",
    "broadband access",
    "Network coverage",
    "mobile coverage",
    "digital gender gap",
    "gender digital divide",
    "colocation data center",
    "cloud storage",
    "cloud platforms",
    "data center",
    "cloud computing",
    "telecom SOE",
    "telecom state-owned enterprise",
    "telecom market liberalization",
    "open to competition",
    "telecom license",
    "mobile license",
    "IXP",
    "ICT regulator",
    "telecom regulator",
    "interconnection",
    "Infrastructure sharing",
    "telecom license",
    "spectrum management",
    "telecom tax",
    "digital tax",
    "national roaming",
]
platforms = [
    "Digital Government",
    "egovernment",
    "public sector digitization",
    "whole-of-government approach",
    "integrated government systems",
    "system integration",
    "e-government portal",
    "single window",
    "one-stop shop",
    "Change management",
    "enterprise service bus",
    "government service bus",
    "National ID",
    "Civil Registration",
    "birth and death registration",
    "birth registration",
    "death registration",
    "Identification systems",
    "authentication system",
    "verification system",
    "e-ID",
    "electronic identification",
    "biometric ID",
    "Dynamic Social Registries",
    "digital certificate",
    "e-authentication",
    "single sign-on",
    "interoperability",
    "enterprise architecture",
    "interoperability framework",
    "Open government",
    "open government data",
    "open data",
    "data exchange",
    "data sharing",
    "Public Financial Management systems",
    "Tax Management Systems",
    "Customs Management Systems",
    "e-Procurement",
    "Human Resources Management Information System",
    "financial management information system",
    "financial management system",
    "financial information management system",
    "financial management and information system",
    "integrated FMIS",
    "integrated financial management information system",
    "tax reporting system",
    "tax payment system",
    "citizen feedback management",
    "grievance redress mechanism",
]

financial_services = [
    "Financial access and usage",
    "Digital financial product",
    "Online banking",
    "Mobile banking",
    "Payment cards",
    "Digital credit",
    "Fintech industry",
    "Remittance prices",
    "Indirect costs",
    "Transaction costs",
    "Fintech",
    "Financial inclusion",
    "National payments system",
    "Regtech",
    "Regulatory technology",
    "AML/CFT requirements",
    "Nonbank e-money issuance",
    "Nonbank financial institution",
    "Online marketplace",
    "Peer-to-peer lending",
    "Insurtech",
    "Digital currency",
    "Central bank digital currency",
    "Cross-Border payments",
    "Digital payments",
    "Government payments",
    "Full service provider (FSP)",
    "Payment service provider (PSP)",
    "Interoperability",
    "API",
    "Digital finance solutions",
    "Cryptocurrency",
    "Cybersecurity",
    "Data privacy",
    "Data protection",
    "Data sharing",
    "AML/CFT",
    "KYC",
    "Payment systems",
    "Payment switch",
    "Payment gateway",
    "Fast payments",
    "Mobile money",
    "e-money",
    "Transaction accounts",
    "Automated clearing house (ACH)",
    "Electronic funds transfer (EFT)",
    "Credit Reporting System",
    "Collateral Registry",
    "Transaction data",
]

businesses = [
    "Digital market",
    "Digital trade",
    "Licensing",
    "Certification standard",
    "Employment opportunities",
    "Digital job creation",
    "Incubator",
    "Accelerator",
    "Tech park",
    "Digital innovation ecosystem",
    "Business ecosystem",
    "Digital startups",
    "Established digital businesses",
    "Platform-based businesses",
    "Data-driven businesses",
    "Verification mechanism",
    "Digital technology",
    "Disruptive technologies",
    "Hardware manufacturing",
    "Information services",
    "Software and IT consulting",
    "Telecommunications",
    "Digital services",
    "Platform economy",
    "Sharing economy",
    "Gig economy",
    "Algorithmic economy",
    "Precision agriculture",
    "e-commerce",
    "Digit commerce",
    "e-business",
    "Industry 4.0",
    "Fintech",
    "E-commerce",
    "Logistics tech",
    "Business management tech",
    "Web services",
    "Big data and analytics",
    "Tech hardware",
    "Edtech",
    "Social network",
    "Security tech",
    "Telecom",
    "Insurance tech",
    "Entertainment tech",
    "Mobility tech",
    "Health tech",
]

skills = [
    "Digital competencies",
    "ICT skills",
    "Digitally competent workforce",
    "Digitally literate citizens",
    "Digital Skills Framework",
    "e-Competence framework",
    "Digital Literacy Global Framework",
    "Digital Skills Gap",
    "ICT Curriculum",
    "Digital Skills Curriculum",
    "digital skills training",
    "Digital literacy",
    "Basic digital skills",
    "Digitally literate",
    "computer literacy",
    "IT skills",
    "digital workforce",
    "IT workers",
    "digitally skilled workforce",
    "digital entrepreneurship",
    "digital start-up",
    "data analytics skills",
    "Coding academy",
    "Coding bootcamps",
    "ICT professions",
    "software engineer",
    "AI skills",
    "big data skills",
    "STEM skills",
    "software developer",
    "application developer",
    "cybersecurity expert",
    "DevOps",
    "Cloud professional",
    "Data Scientists",
    "Database managers",
    "digital training for public sector employee",
    "data analytics for government",
    "IT government officials",
    "IT officials",
    "Edtech companies",
    "Ed-tech companies",
    "Apprentices programs",
    "digital training provider",
    "digital incubator",
    "digital accelerator",
    "tech hubs",
    "National Research and Education Network (NREN)",
]

safeguards = [
    "cyber threats",
    "cyber crime",
    "computer emergency response team (CERT)",
    "enterprise security architecture (ESA)",
    "critical information infrastructure protection (CIIP)",
    "online protection",
    "CSIRT",
    "CERT",
    "cyberattack",
    "information security",
    "cyber resilience",
    "digital security",
    "online safety",
    "cybersecurity strategy",
    "Data regulation",
    "Information privacy",
    "data protection law",
    "data privacy law",
    "access to information",
    "right to information",
    "data protection bill",
    "data privacy bill",
    "information quality and integrity",
    "data protection authority",
    "data protection agency",
    "data commissioner",
    "PKI",
    "encryption",
    "data controllers",
    "data processors",
    "DP&P",
    "digital trust",
    "Child online protection",
    "Online consumer protection",
]

use_cases = [
    "NREN",
    "national research and education network",
    "RREN",
    "regional research and education network",
    "campus network",
    "telemedicine",
    "medical network",
    "health network",
    "rural healthcare",
    "health care access",
    "education access",
    "research network",
    "education network",
    "education management information system",
    "health management information system",
    "hospital management system",
    "land registration system",
    "cadastre system",
    "land registration and cadastre system",
    "social protection management information system",
    "electronic passport",
    "e-Passport",
    "voter registration",
    "voter ID",
    "business registry",
    "corporate registry",
    "company registry",
    "taxpayer registry",
    "civil service registry",
    "public employee registry",
    "civil servant registry",
    "beneficiary registry",
    "social protection system",
    "social protection registry",
    "vaccination registry",
    "patient registry",
    "hospital registry",
    "healthcare management system",
    "health care management system",
    "school registry",
    "teacher registry",
    "student registry",
    "drivers license registry",
    "vehicle registry",
    "land registry",
    "land registration",
    "fixed asset registry",
    "immovable asset registry",
    "Payroll Management System",
    "Asset Management",
    "Debt Management",
    "Treasury Single Account",
    "e-commerce",
    "electronic commerce",
    "online commerce",
    "data-driven agriculture",
    "Precision farming",
    "Agtech solutions",
    "Crop management",
    "Smart irrigation",
    "weather stations",
    "Agricultural sensors",
    "Farm-to-table traceability",
    "Remote monitoring",
    "Livestock management",
    "precision farming",
    "e-agriculture",
    "agritech",
    "Telemedicine",
    "Electronic health records",
    "Wearable devices",
    "Health analytics",
    "mHealth apps",
    "Virtual care",
    "Personalized medicine",
    "Health data interoperability",
    "patient management system",
    "health tech",
    "education management information system (EMIS)",
    "Learning management system (LMS)",
    "E-learning platforms",
    "Open educational resources",
    "Massive Open Online Courses (MOOCs)",
    "adaptive learning",
    "remote learning",
    "blended learning",
    "computer labs",
    "ICT laboratories",
    "multimedia labs",
    "e-readers",
    "ICT skills for teachers",
    "technology for teacher training",
    "teachers' digital skills",
    "e-libraries",
    "ICT in schools",
    "Intelligent transportation systems",
    "fleet management",
    "Smart traffic management",
    "Shared mobility",
    "e-mobility",
    "smart mobility",
    "mobility as a service",
    "electric vehicle",
    "car sharing",
    "electronic fleet management",
    "ride prediction",
    "Energy management systems",
    "Smart grid technologies",
    "smartgrid",
    "OPGW",
    "smart factories",
    "Industrial IoT",
    "Supply chain traceability",
    "e-commerce",
    "smart city",
    "smart cities",
    "Data analytics",
    "big data",
    "open data",
    "artificial intelligence",
    "machine learning",
]

# convert each list to a string
infrastructure_str = ", ".join(infrastructure)
platforms_str = ", ".join(platforms)
financial_services_str = ", ".join(financial_services)
businesses_str = ", ".join(businesses)
skills_str = ", ".join(skills)
safeguards_str = ", ".join(safeguards)
use_cases_str = ", ".join(use_cases)

topic = {}
topic_lists = [
    infrastructure_str,
    platforms_str,
    financial_services_str,
    businesses_str,
    skills_str,
    safeguards_str,
    use_cases_str,
]
topic_names = [
    "infrastructure",
    "platforms",
    "financial_services",
    "businesses",
    "skills",
    "safeguards",
    "use_cases",
]

for name, list in zip(topic_names, topic_lists):
    topic[name] = list
